### ISSUE TITLE
Missing IBM Copyright headers from MP GraphQL Sample Code

### ISSUE THREAD

**Issue by andymc12** [fmarchioni/mastertheboss#14]
Hi @fmarchioni - I saw your blog post on MP GraphQL at http://www.mastertheboss.com/javaee/eclipse-microservices/getting-started-with-graphql-using-java-applications - nice article!

The sample code that you use and currently host in this repo is intellectual property of IBM licensed under the Eclipse Public License, but the copy of the code you have on this site has removed those copyright headers.  For example:
The WeatherService.java file from here:
https://github.com/fmarchioni/mastertheboss/blob/master/micro-services/mp-graphql/src/main/java/graphql/sample/WeatherService.java
 
is the same as this file from the [OpenLiberty/sample-mp-graphql](https://github.com/OpenLiberty/sample-mp-graphql) repository, but without the "io.openliberty" package or the IBM copyright header:
https://github.com/OpenLiberty/sample-mp-graphql/blob/276906169284333c09cacfe496d4c561106476a6/src/main/java/io/openliberty/graphql/sample/WeatherService.java

Repackaging is allowed under the EPL, but removal of the copyright header is not.  Can you please add the copyright headers back to these source files?

Thanks, Andy

**Comment by fmarchioni** [comment]
Hi Andy,
apologizes for the issue. I have removed the example from github and I have
requested our web site contributors to rewrite a GraphQL example from
scratch.
The online article will soon be updated accordingly. Apologize for the
inconvenience again,
best regards
Francesco


Il giorno gio 24 set 2020 alle ore 21:22 Andy McCright <
notifications@github.com> ha scritto:

**Comment by andymc12** [comment]
Thanks for the quick response!  If there is anything I can do to help with the new example, please let me know.
