### ISSUE TITLE
License

### ISSUE THREAD

**Issue by merando** [fmarchioni/mastertheboss#2]
We like to use mastertheboss, however, we need a proper license on the project. Something like Apache2, MIT or BSD would suit the project well. Would it be possible to add one?

**Comment by fmarchioni** [comment]
Hi,
sorry for the delay. I've added a MIT licensing info on the project's home
page at github
Regards
Francesco

2016-05-03 10:07 GMT+02:00 Matthias Kricke <notifications@github.com>:

**Comment by merando** [comment]
Thanks @fmarchioni . I made a pull request to add a proper LICENSE file to the project.

**Comment by merando** [comment]
The license question ins answered and a MIT license is added. So we can close this issue
