### ISSUE TITLE
Fails on Wildfly 10

### ISSUE THREAD

**Issue by n0en** [fmarchioni/mastertheboss#5]
I've tried running this on Wildfly 10 and it fails with the following exception when trying to list the queues:
java.lang.IllegalArgumentException
at org.jboss.dmr.ModelValue.asList(ModelValue.java:140)
at org.jboss.dmr.ModelNode.asList(ModelNode.java:1384)
at com.mastertheboss.jmsbrowser.EJBBrowser.getListQueues(EJBBrowser.java:160)

**Comment by pprivately** [comment]
It seems, that code fails on jBOSS/WildFly implementations where activemq replaced hornet-mq (WildFly 10+). Easy change in line 151 of com.mastertheboss.jmsbrowser.EJBBrowser.java. Will you rebuild or take subsystem name form env? Enventually try both in try/catch block somewhere circa EJBBrowser.java:160.
