### ISSUE TITLE
PGXADataSource wrong configuration?

### ISSUE THREAD

**Issue by ffroliva** [fmarchioni/mastertheboss#50]
Is this line correct?

https://github.com/fmarchioni/mastertheboss/blob/4f058f0ab11533c848f4feb6342b6de5fc77059b/jbpm/business-application-postgresql/business-application-service/src/main/resources/application.properties#L38

Shouldn't it be:

```
spring.datasource.xa.data-source-class-name=org.postgresql.xa.PGXADataSource
spring.datasource.driver-class-name=org.postgresql.Driver
```

**Comment by fmarchioni** [comment]
Hi,
I think the DS driver class name is not needed to run the example:

spring.datasource.driver-class-name=org.postgresql.Driver

I have used as a template the jbpm starters (
https://github.com/business-applications/01-tutorial-first-business-application/blob/master/business-application-service/src/main/resources/application-postgres.properties)
where that line is not included as well.
regards
Francesco

Il giorno mar 5 lug 2022 alle ore 14:36 Flavio Oliva <
***@***.***> ha scritto:
