### ISSUE TITLE
Error in Running Batch jobs in J2SE applications

### ISSUE THREAD

**Issue by tcesenthil** [fmarchioni/mastertheboss#6]
I created the project mentioned in the example of [this article ](http://www.mastertheboss.com/javaee/batch-api/running-batch-jobs-in-j2se-applications#) and tried running using jberet in java SE mode. But, i have been facing several issues while executing from my windows command prompt as a java SE application.

The issue details are listed here in this stackoverflow question.

https://stackoverflow.com/questions/46537209/weld-001409-ambiguous-dependencies-for-type-stepcontext-with-qualifiers-defaul

Could you help in sharing your project, especially the POM and any other settings or configurations to run the final executable JAR in command prompt

**Comment by fmarchioni** [comment]
Finally I have updated the example to run with Jakarta EE environment and published the code here.
https://www.mastertheboss.com/java-ee/batch-api/running-batch-jobs-in-j2se-applications/
