### ISSUE TITLE
"How to enable CORS in WildFly" fails

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [fmarchioni/mastertheboss#60]
I'm trying to run commands from this tutorial, but cmd prints the following in the first step:
![image](https://user-images.githubusercontent.com/3578953/207715544-10f69865-f96a-4844-b352-80a4fdd50098.png)
Using Wildfly 22

**Comment by fmarchioni** [comment]
Thanks for the report. The article has been fixed
