### ISSUE TITLE
Managing Config

### ISSUE THREAD

**Issue by hirenshah** [fmarchioni/mastertheboss#9]
Hi,

This isn't exactly an issue, and more of a question instead.  I have been using mastertheboss quite a bit as a point of reference, whilst I have spent a considerable amount of time researching and playing the trial and error game. 

So the question, I have 10 different servers, each running multiple JBoss instances (not in domain mode). 
 The standalone.xml files vary a little between each and it isn't each trying to manage them all.   Without setting up a whole platform that would cover this plus any future activities, what is the best way to manage just this setup alone?

Thanks :)

**Comment by fmarchioni** [comment]
Sorry for unattending this request and thanks for following my tutorial. Overall, the purpose of the "issues" area is about bug founds in the tutorials. I'd say you could opt for properties if all your servers have the same subsystems. other than that, Domain should be the recommended approach.
